apiVersion: v1
kind: Service
metadata:
  name: messaging-app
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    color: blue
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-green
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    color: green
  ports:
    - port: 8000
      targetPort: 8000
